name: industrial_ci

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - { ROS_DISTRO: noetic, ROS_REPO: ros }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "ros-industrial/industrial_ci@master"
        env: ${{ matrix.env }}
